### ISSUE TITLE
Gemeinsamkeiten der Widgets definieren

### ISSUE THREAD

**Issue by ybugge** [dhaeb/LinkedDataBrowser#13]
Akzeptanzkriterien:
- Entgegennahme der Parameter "subject" und "endpoint" 
- Asynchrone Kommunikation zwischen Client und Server
- Grundaussehen/Grundfunktionen (Bsp.: Minimieren) der Widgets

**Comment by dhaeb** [comment]
vor allem im Bezug auf mögliche neue Widgets für das Angular Dashboard Framework relevant
